<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DS0105EN-SkillsNetwork/labs/Module2/images/SN_web_lightmode.png" width="300" alt="cognitiveclass.ai logo">
</center>

My Notebook

Introduction

Data Science Languages
    SQL
    Python
    R

Data Science Libraries
    Python
        NumPy
        Pandas
        Matplotlib

| Data Science Tools |
| -------------------| 
| Apache Spark       |  
| Jupyter Notebook   | 
| Microsoft Power BI |  
| Tableau            |
| Tensor Flow        |

Arithmatic Expression Examples

In [1]:
code = compile("5 + 4", "<string>", "eval")
eval(code)

9

Multiply and Add Numbers

In [2]:
5 * (3 +5)

40

Convert Minutes to Hours

In [16]:
Minutes = 324
Convert = Minutes / 60 
print(str(Convert) + " Hours")

5.4 Hours

Objectives

Exercise 2 - Create a markdown cell with the title of the notebook. (1 pt)

Exercise 3 - Create a markdown cell for an introduction. (1 pt)

Exercise 4 - Create a markdown cell to list data science languages. (3 pts)

Exercise 5 - Create a markdown cell to list data science libraries. (3 pts)

Exercise 6 - Create a markdown cell with a table of Data Science tools. (3 pts)

Exercise 7 - Create a markdown cell introducing arithmetic expression examples. (1 pt)

Exercise 8 - Create a code cell to multiply and add numbers. (2 pts)

Exercise 9 - Create a code cell to convert minutes to hours. (2 pts)

Exercise 10 -Insert a markdown cell to list Objectives. (3 pts)

Exercise 11 - Create a markdown cell to indicate the Authorâ€™s name. (2 pts)

Exercise 12 - Share your notebook through GitHub (3 pts)

Exercise 13 - Take a screenshot of the first page of the notebook. (1 pt)

Author: Quoc Tran